gui:
  theme:
    activeBorderColor:
      - '#f9e2af'    # Žlutá (byla modrá)
      - bold
    inactiveBorderColor:
      - '#a6adc8'    # Šedá (zůstává)
    optionsTextColor:
      - '#f9e2af'    # Žlutá (byla modrá)
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f9e2af'    # Žlutá (byla modrá)
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'    # Žlutá
