add_newline = false

# HLAVNÃ FORMÃT
# VÅ¡imni si dvojitÃ½ch lomÃ­tek \\( a \\)
format = """
[â”Œâ”€â”€\\(](bold blue)$username[@](bold white)$hostname[\\)-](bold blue)$directory$git_branch
$character"""

# UÅ½IVATEL
[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style)"
show_always = true

# HOSTNAME
[hostname]
style = "bold white"
ssh_only = false
format = "[$hostname]($style)"

# SLOÅ½KA
[directory]
style = "cyan bold"
read_only = " ğŸ”’"
truncation_length = 3
# I tady musÃ­me zdvojit lomÃ­tka: \\[ a \\]
format = "[ \\[ ](bold blue)[$path]($style)[ \\] ](bold blue)"

# DRUHÃ Å˜ÃDEK
[character]
success_symbol = "[â””â”€â¯](bold green)"
error_symbol = "[â””â”€â¯](bold red)"
